alias k=kill
alias k1="kill -HUP"      # hang up
alias k2="kill -INT"      # interrupt
alias k3="kill -QUIT"     # quit
alias k4="kill -ILL"
alias k5="kill -TRAP"
alias k6="kill -ABRT"     # abort
alias k7="kill -EMT"
alias k8="kill -FPE"
alias k9="kill -KILL"     # non-catchable, non-ignorable kill
alias k10="kill -BUS"
alias k11="kill -SEGV"
alias k12="kill -SYS"
alias k13="kill -PIPE"
alias k14="kill -ALRM"    # alarm clock
alias k15="kill -TERM"    # software termination signal
alias k16="kill -URG"
alias k17="kill -STOP"
alias k18="kill -TSTP"
alias k19="kill -CONT"
alias k20="kill -CHLD"
alias k21="kill -TTIN"
alias k22="kill -TTOU"
alias k23="kill -POLL"
alias k24="kill -XCPU"
alias k25="kill -XFSZ"
alias k26="kill -VTALRM"
alias k27="kill -PROF"
alias k28="kill -WINCH"   # Gracefully shutdown the worker processes
alias k29="kill -PWR"
alias k30="kill -USR1"    # Reopen the log files
alias k31="kill -USR2"    # Upgrade Executable on the fly
alias k32="kill -RESV"
alias k33="kill -RTMIN"
alias k34="kill -RTMIN+1"
alias k35="kill -RTMIN+2"
alias k36="kill -RTMIN+3"
alias k37="kill -RTMIN+4"
alias k38="kill -RTMIN+5"
alias k39="kill -RTMIN+6"
alias k40="kill -RTMIN+7"
alias k41="kill -RTMAX-7"
alias k42="kill -RTMAX-6"
alias k43="kill -RTMAX-5"
alias k44="kill -RTMAX-4"
alias k45="kill -RTMAX-3"
alias k46="kill -RTMAX-2"
alias k47="kill -RTMAX-1"
alias k48="kill -RTMAX"

